hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    account-service:
        path: /orders/**
        serviceId: order-service
        stripPrefix: false
        sensitiveHeaders:

    statistics-service:
        path: /members/**
        serviceId: member-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 7000
