spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  profiles:
    active: native
  application:
    name: config-server

server:
  port: 8888

security:
  user:
    password: root
